apiVersion: v1
kind: Template
labels:
  template: temperature-service
  app: temperature-service
metadata:
  annotations:
    description: Spring Boot Temperature Service to test Spring Boot Admin environment
    iconClass: icon-java
    tags: microservice,spring,spring-boot
    author: Ricardo Zanini <ricardozanini@gmail.com>
    url: https://github.com/ricardozanini/spring-boot-admin-k8s
  name: temperature-service
parameters:
- description: Spring Boot Admin URL. If it's deployed locally, use service url (e.g. http://spring-boot-admin:8080)
  displayName: Spring Boot Admin URL
  name: SPRING_BOOT_ADMIN_URL
  required: true
  value: http://spring-boot-admin.<namespace>.svc:8080
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: temperature-service
    name: temperature-service
  spec:
    tags:
      - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: temperature-service
    name: temperature-service
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: temperature-service:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/ricardozanini/spring-boot-admin-k8s.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS_APPEND
          value: -pl service --also-make
        - name: ARTIFACT_DIR
          value: service/target
        - name: MODULE_DIR
          value: service
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: temperature-service
    name: temperature-service
  spec:
    replicas: 1
    selector:
      deploymentconfig: temperature-service
      app: temperature-service
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: temperature-service
          deploymentconfig: temperature-service
      spec:
        containers:
        - env:
          - name: SPRING_BOOT_ADMIN_URL
            value: ${SPRING_BOOT_ADMIN_URL}
          image: temperature-service
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: temperature-service
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 400m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - temperature-service
        from:
          kind: ImageStreamTag
          name: temperature-service:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: temperature-service
    name: temperature-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: temperature-service
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: temperature-service
    name: temperature-service
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: temperature-service
      weight: 100